server:
  port: 8082
  servlet:
    context-path: /app1
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
#    client:
#      grant-type: implicit
#      client-id: foo
#      client-secret:  bar
#      access-token-uri: http://localhost:8080/sso-server/oauth/token
#      user-authorization-uri: http://localhost:8080/sso-server/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/sso-server/user/me
      jwt:
        key-uri: http://localhost:8080/sso-server/oauth/token_key
#      jwk:
#        key-set-uri: http://localhost:8080/sso-server/.well-known/jwks.json
  basic:
    enabled: false